name: question-74910046
# https://stackoverflow.com/questions/74910046/how-do-i-reference-the-deployment-environment-name-in-github-actions-workflow-ya

on:
  workflow_dispatch:
  
env:
  env_name: production-74910046
  env_url: https://stackoverflow.com/questions/74910046/how-do-i-reference-the-deployment-environment-name-in-github-actions-workflow-ya

jobs:
  test:
    runs-on: ubuntu-latest

    environment: 
      name: $env_name
      url: $env_url
    
    steps:
      - name: context information
        run: echo '${{ toJSON(env) }}'
